const daten = [
  {
    "PersonID": 1,
    "Name": "Abel, August",
    "Beruf": "Journalist",
    "Berufsgruppe": "Medien",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1887,
    "Geburtsdatum/-ort": "* 19. Dez. 1887 Gelsenkirchen",
    "Sterbejahr": 1962,
    "Sterbedatum/-ort": "† 18. Aug. 1962 Frankfurt/M.",
    "Religion": "kath.",
    "Religion_Gruppe": "Christlich",
    "Ausreiseort": "Stadt(?), Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1934,
    "Emigrationsweg": "1934 Tanganjika (Tansania) [Kolonie GB] → 1948 Deutschland",
    "Emigrationsland": "Tansania, Deutschland",
    "Detailtext": "1934 Emigr. nach Afrika. Farmer in Tanganjika. 1948 Rückkehr nach Deutschland, freier Journalist."
  },
  {
    "PersonID": 2,
    "Name": "Abel, Emil",
    "Beruf": "prof. of chemistry",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Chemie",
    "Geburtsjahr": 1875,
    "Geburtsdatum/-ort": "* Vienna 2 June 1875",
    "Sterbejahr": 1958,
    "Sterbedatum/-ort": "† London 3 Apr. 1958",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 GB",
    "Emigrationsland": "GB",
    "Detailtext": "1938 mem. fac, T.H. Vienna: 1938 dismissed. Concurr. 1938 emigr. to U.K. Cont. res. work, incl. dev. of dry cell battery. Mem. Free Aus. Movt. Est. successful new school of chemists at T.H. Vienna. E.A, with Rudolf Wegscheider, was a leading physical chemist in period between the two World Wars. Carried out internationally recognized res. work, esp. in fields of chemical catalysis (intermediate-reaction catalysis), kinetics (isotope effect) and thermodynamics."
  },
  {
    "PersonID": 3,
    "Name": "Abel, Paul, Dr. jur.",
    "Beruf": "Rechtsanwalt",
    "Berufsgruppe": "Sozialwissenschaften",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1874,
    "Geburtsdatum/-ort": "* 21. März 1874 Wien",
    "Sterbejahr": 1971,
    "Sterbedatum/-ort": "† 10. Mai 1971 London",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 GB",
    "Emigrationsland": "GB",
    "Detailtext": "1938 Mitgl. u. 1. Vizepräs. Ausschuß der Wiener Rechtsanwaltskammer. Wiss. Tätigkeit, zahlr. Veröffentl. in österr. u. internat. FachZs. Bis 1938 u.a. VorstMitgl. Wiener Juristische Gesellschaft, Vizepräs. österr. Landesgruppe Association Internationale pour la protection de la propriété industrielle, usw. 1938 Emigr. London."
  },
  {
    "PersonID": 4,
    "Name": "Abeles, Paul William",
    "Beruf": "civil engineer",
    "Berufsgruppe": "Technik",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Technik",
    "Geburtsjahr": 1897,
    "Geburtsdatum/-ort": "* Mistelbach near Vienna 17 Jan. 1897",
    "Sterbejahr": 1977,
    "Sterbedatum/-ort": "<i>† 1977</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 GB",
    "Emigrationsland": "GB",
    "Detailtext": "1939 emigr. to U.K."
  },
  {
    "PersonID": 5,
    "Name": "Abeles, Robert Heinz",
    "Beruf": "prof. of biochemistry",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Biologie, Chemie",
    "Geburtsjahr": 1926,
    "Geburtsdatum/-ort": "* Vienna 14 Jan. 1926",
    "Sterbejahr": 2000,
    "Sterbedatum/-ort": "<i>† 2000</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1939 emigr. to U.S."
  },
  {
    "PersonID": 6,
    "Name": "Abelmann, Walter H",
    "Beruf": "prof. of medicine",
    "Berufsgruppe": "Medizin",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1921,
    "Geburtsdatum/-ort": "* Frankfurt/M 16 May 1921",
    "Sterbejahr": 2011,
    "Sterbedatum/-ort": "<i>† 2011</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Frankfurt/Main, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Schweiz → 1939 USA",
    "Emigrationsland": "Schweiz, USA",
    "Detailtext": "1933 emigr. to Switz. 1939 att. Gym, Zurich. 1939 emigr. to U.S. 1939–40 att. Univ. Virginia, Charlottesville."
  },
  {
    "PersonID": 7,
    "Name": "Aber, Adolf",
    "Beruf": "musicologist",
    "Berufsgruppe": "Geisteswissenschaften",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Kunst, Musik",
    "Geburtsjahr": 1893,
    "Geburtsdatum/-ort": "* Apolda, Thuringia, Ger. 28 Jan. 1893",
    "Sterbejahr": 1960,
    "Sterbedatum/-ort": "† London 21 May 1960",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Leipzig, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 GB",
    "Emigrationsland": "GB",
    "Detailtext": "1933 music critic for Leipziger Neueste Nachrichten and Allg. Musikztg. Active in fostering mod. music, giving support to cond. Hermann Scherchen’s perfs. of Ernst Křenek’s Jonny spielt auf and Kurt Weill’s Mahagonny. 1933 emigr. to U.K. 1933– with Novelle and Co. publ. firm."
  },
  {
    "PersonID": 8,
    "Name": "Aber, Felix, Dr. phil.",
    "Beruf": "Rabbiner",
    "Berufsgruppe": "Geistliche",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1895,
    "Geburtsdatum/-ort": "* 11. Apr. 1895 Breslau",
    "Sterbejahr": 1964,
    "Sterbedatum/-ort": "† 14. Jan. 1964 New York",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1939 Emigr. USA."
  },
  {
    "PersonID": 9,
    "Name": "Abraham, Claude Kurt (fmly. Kurt Jakob Abraham)",
    "Beruf": "prof. of French",
    "Berufsgruppe": "Geisteswissenschaften",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Sprache",
    "Geburtsjahr": 1931,
    "Geburtsdatum/-ort": "* Lorsch, Hessen, Ger. 13 Dec. 1931",
    "Sterbejahr": 2020,
    "Sterbedatum/-ort": "<i>† 2020</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Lorsch, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 Frankreich → 1946 USA",
    "Emigrationsland": "Frankreich, USA",
    "Detailtext": "1938 emigr. to Fr; lived with rels. in Paris; parents arrived Jan. 1946 emigr. to U.S. Supported by rels."
  },
  {
    "PersonID": 10,
    "Name": "Abraham, Heinz, Dr.",
    "Beruf": "Diplomat, Historiker",
    "Berufsgruppe": "Geisteswissenschaften, Staatsdienst",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Geschichte",
    "Geburtsjahr": 1911,
    "Geburtsdatum/-ort": "* 30. Juni 1911 Allenstein, Ostpr.",
    "Sterbejahr": 1992,
    "Sterbedatum/-ort": "<i>† 1992</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Breslau, Deutschland/Polen",
    "Ausreiseland": "Deutschland/Polen",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Moskau (UdSSR/Russland) → 1937 Spanien → 1939 Frankreich → (Jahr ?) Moskau (UdSSR/Russland) → (Jahr ?) Deutschland",
    "Emigrationsland": "UdSSR/Russland, Spanien, Frankreich, Deutschland",
    "Detailtext": "1937–39 Teiln. Span. Bürgerkrieg, anschl. Internierung in Frankr.; Rückkehr in die UdSSR, Architekt. 1939 Teiln. Span. Bürgerkrieg, anschl. Internierung in Frankr.; Rückkehr in die UdSSR, Architekt."
  },
  {
    "PersonID": 11,
    "Name": "Abraham, Henry J(ulian)",
    "Beruf": "prof. of political science",
    "Berufsgruppe": "Sozialwissenschaften",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1921,
    "Geburtsdatum/-ort": "* Offenbach, Hessen, Ger. 25 Aug. 1921",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Frankfurt/Main, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1937,
    "Emigrationsweg": "1937 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1937 att. Realgym, Frankfurt/M; worked as printer’s apprentice. Apr. 1937 emigr. to U.S; stayed with aunt; delivered newspapers."
  },
  {
    "PersonID": 12,
    "Name": "Abraham, Paul (fmly. Pál A.)",
    "Beruf": "composer of light opera, film scores",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1892,
    "Geburtsdatum/-ort": "* Apatin, Hung. 2 Nov. 1892",
    "Sterbejahr": 1960,
    "Sterbedatum/-ort": "† Hamburg 6 May 1960",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Stadt(?), Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Frankreich → 1938 USA → 1956 Deutschland",
    "Emigrationsland": "Frankreich, USA, Deutschland",
    "Detailtext": "1933 film version and Milan première of Blume; P.A.’s music banned by Nazi regime. 1933 emigr. to Paris; same yr. Vienna première of Ball im Savoy. 1938 premières of P.A.’s operettas in Vienna (see “other works” below)."
  },
  {
    "PersonID": 13,
    "Name": "Abrahamowicz, Uriel (urspr. Walter)",
    "Beruf": "Gewerkschaftler",
    "Berufsgruppe": "Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1915,
    "Geburtsdatum/-ort": "* 29. Sept. 1915 Wien",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1934,
    "Emigrationsweg": "1934 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1934 Emigr. Pal. mit C-Zertifikat; Mitgl. Haganah, I.D.F."
  },
  {
    "PersonID": 14,
    "Name": "Abramowitsch, Ruth (pseud. 1933–1950s Ruth Sorel)",
    "Beruf": "dancer, choreographer, teacher",
    "Berufsgruppe": "Kunst, Sozial-/Bildungswesen",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1907,
    "Geburtsdatum/-ort": "* Halle/Saale, Saxony, Ger. 1907",
    "Sterbejahr": 1974,
    "Sterbedatum/-ort": "<i>† 1974</i>",
    "Religion": "Jewish(?)",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Berlin, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Polen → 1941 Südamerika → 1945 Kanada → 1950 Polen",
    "Emigrationsland": "Polen, Südamerika, Kanada",
    "Detailtext": "1933 prima ballerina, State Opera Berlin; dramatic dancer and choreographer; solo dance concerts with partner Georg Groke; assist. dir, children’s dance group, State Opera, Berlin. Spring 1933 emigr. to Pol. Ballet perfs. and tours in Pol, Pal, and S. Am. with partner G. Groke under pseud. Ruth Sorel. During W. W. II emigr. to S. Am, later to Can."
  },
  {
    "PersonID": 15,
    "Name": "Abravanel, Maurice (fmly. de Abravanel)",
    "Beruf": "conductor, music director",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1903,
    "Geburtsdatum/-ort": "* Salonica, Gr. 6 Jan. 1903",
    "Sterbejahr": 1993,
    "Sterbedatum/-ort": "<i>† 1993</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Stadt(?), Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Frankreich → 1936 USA",
    "Emigrationsland": "Frankreich, USA",
    "Detailtext": "1933 left Ger. to cond. in other countries: 1933 for Balanchine at Paris Ballet (première of Bertolt Brecht-Weill’s Seven Deadly Sins, Fr. première of Brecht-Weill’s Mahagonny); 1933–34 in London, Rome and Geneva. 1936 cond. with Aust. Broadcasting Commn. 1936 emigr. to U.S. with recommendation of Bruno Walter and Wilhelm Furtwängler for cond. position at Metropolitan Opera, New York; became the youngest cond. to work with Metropolitan Opera; revived Saint-Saëns’ Samson et Dalila; left Metropolitan."
  },
  {
    "PersonID": 16,
    "Name": "Abt, Frieda, geb. Nussbaum",
    "Beruf": "Fürsorgerin, Museumsdirektorin",
    "Berufsgruppe": "Sozial-/Bildungswesen, Staatsdienst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1904,
    "Geburtsdatum/-ort": "* 14. Aug. 1904 Fulda",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 GB → 1939 Südafrika",
    "Emigrationsland": "GB, Südafrika",
    "Detailtext": "1939 Emigr. GB, Dez. 1939 S-Afrika."
  },
  {
    "PersonID": 17,
    "Name": "Abt, Harry, Dr. phil.",
    "Beruf": "Prediger, Pädagoge",
    "Berufsgruppe": "Geistliche, Sozial-/Bildungswesen",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1900,
    "Geburtsdatum/-ort": "* 31. Okt. 1900 Weener, Hannover",
    "Sterbejahr": 1977,
    "Sterbedatum/-ort": "† 11. Apr. 1977 Johannesburg, S-Afrika",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Breslau, Deutschland/Polen",
    "Ausreiseland": "Deutschland/Polen",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 GB → 1939 Südafrika",
    "Emigrationsland": "GB, Südafrika",
    "Detailtext": "1939 OberstudDir. am Jüd. Reformrealgymn. der SynGde. Breslau. Aug. 1939 Emigr. GB, Dez. 1939 nach Südafrika zus. mit Ehefrau u. 2 Kindern mit Sondervisum durch Vermittlung des South African Jew. Board Deputies. Lehrer für Hebr. in jüd. Kinderheim, Vortragstätigkeit für den South African Jew. Board Deputies."
  },
  {
    "PersonID": 18,
    "Name": "Abusch, Alexander",
    "Beruf": "Politiker, Publizist",
    "Berufsgruppe": "Politik, Medien",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1902,
    "Geburtsdatum/-ort": "* 14. Febr. 1902 Nürnberg",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Saarbrücken (Saargebiet/Deutschland) → 1935 Prag (CSR/Tschechien) → 1937 Frankreich → 1941 Mexiko → 1946 Berlin (Deutschland)",
    "Emigrationsland": "Saargebiet/Deutschland, CSR/Tschechien, Frankreich, Mexiko, Deutschland",
    "Detailtext": "1933 mit Zustimmung des ZK Emigr. ins Saargeb., 1935 RedMitgl. Arbeiterzeitung Saarbrücken; 1935 Chefred. illeg. Ztg. Die Rote Fahne in Prag; Deleg. sog. Brüsseler (Okt. 1935) u. Berner (Jan./Febr. 1937 in Frankr., Mitgl. KPD-Ltg. Paris; Hauptmitarb. Deutsche Volkszeitung u. Der Gegen-Angriff, zeitw. Chefred., Ps. Ernst Bayer, weitere Deckn. Walter Meier, Alexander Süskind, Henri. Nach Kriegsausbruch interniert u.a. in Damagny-sur-Orne, Le Vernet, Bassens bei Bordeaux; Juni 1941 Hg. Zs. Freies Deutschland, Ausschußmitgl."
  },
  {
    "PersonID": 19,
    "Name": "Acht, Peter (fmly. Maurycy Oskar)",
    "Beruf": "journalist",
    "Berufsgruppe": "Medien",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1898,
    "Geburtsdatum/-ort": "* Lemberg, Galicia. Aus. (Lvov, U.S.S.R.) 9 June 1898",
    "Sterbejahr": 1974,
    "Sterbedatum/-ort": "† Vienna 25 June 1974",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1936,
    "Emigrationsweg": "1936 Prag (CSR/Tschechien) → 1938 Frankreich → 1946 Österreich",
    "Emigrationsland": "CSR/Tschechien, Frankreich, Österreich",
    "Detailtext": "1936 briefly arrested, then emigr. to Prague, 1938 emigr. to Paris. Interned in camps Les Milles and Nîmes. 1946 leader of K.P.Ö. section in Lyons. Mar. 1946 returned to Vienna."
  },
  {
    "PersonID": 20,
    "Name": "Ackerknecht, Erwin Henry (Heinz), Dr. med.",
    "Beruf": "Hochschullehrer",
    "Berufsgruppe": "Sozial-/Bildungswesen",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1906,
    "Geburtsdatum/-ort": "* 1. Juni 1906 Stettin",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "Diss.",
    "Religion_Gruppe": "Konfessionslos",
    "Ausreiseort": "Berlin, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Prag (CSR/Tschechien) → 1933 Frankreich → 1941 Trinidad [Kolonie GB] → 1941 USA → 1957 Schweiz",
    "Emigrationsland": "CSR/Tschechien, Frankreich, Trinidad, USA, Schweiz",
    "Detailtext": "1933 Assist. für Neurologie u. Psychiatrie Berlin. Ab 1933, vorüberg. Haft. Anfang Juni 1933 auf Beschluß der Gruppe Flucht in die CSR. Juni/Juli 1933 bei Leo Trockij in der Türkei, Aug. 1933 nach Frankr., bis 1941 nach mehrwöchiger Internierung auf Trinidad in die USA. Packer u. Krankenpfleger. 1957 Prof. für Gesch. der Medizin in Madison/Wisc.; 1957–71 (Emeritierung) ETH Zürich, zahlr. Vortragsreisen in den USA u. Europa, 1957 Am. Assn. of Medicine History."
  },
  {
    "PersonID": 21,
    "Name": "Ackermann, Manfred",
    "Beruf": "Parteifunktionär, Gewerkschaftler",
    "Berufsgruppe": "Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1898,
    "Geburtsdatum/-ort": "* 1. Nov. 1898 Nikolsburg, Mähren",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "Diss.",
    "Religion_Gruppe": "Konfessionslos",
    "Ausreiseort": "Stadt(?), Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 Belgien → 1938 Frankreich → 1940 USA → 1964 Österreich",
    "Emigrationsland": "Belgien, Frankreich, USA, Österreich",
    "Detailtext": "1938 aufgrund Schuschnigg-Amnestie entlassen. RSÖ-Vertr. in Komitee zur Koordinierung der pol. Aktion von Sozialisten u. Kommunisten angesichts des drohenden dt. Einmarschs, dann mit falschem Paß auf den Namen Hübner Flucht über Italien u. Schweiz nach Brüssel. Anfang Apr. 1938 Teiln. Brüsseler Tagung der österr. Sozialisten, auf der sich die führenden SDAP- u. RSÖ-Vertr. im Exil auf eine gesamtdt. Revolution festlegten u. die Forderung nach Wiederherstellung der Selbständigkeit Österreichs verwarfen."
  },
  {
    "PersonID": 22,
    "Name": "Ackermann, Otto",
    "Beruf": "conductor, music director, music producer",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1909,
    "Geburtsdatum/-ort": "* Bucharest, Rum. 5 Oct. 1909",
    "Sterbejahr": 1960,
    "Sterbedatum/-ort": "† Bern 2 Mar. 1960",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Brünn, CSR/Tschechien",
    "Ausreiseland": "CSR/Tschechien",
    "Ausreisejahr": 1935,
    "Emigrationsweg": "1935 Schweiz",
    "Emigrationsland": "Schweiz",
    "Detailtext": "1935 opera dir, Deutsches Theater, Brno, C.S.R. 1935 emigr. to Switz. 1935–47 cond. and opera prod, munic. operas of Bern, Zurich, Lucerne, Geneva."
  },
  {
    "PersonID": 23,
    "Name": "Ackermann, Paul Kurt",
    "Beruf": "prof. of German",
    "Berufsgruppe": "Geisteswissenschaften",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Sprache",
    "Geburtsjahr": 1919,
    "Geburtsdatum/-ort": "* Bremen, Ger. 5 Sept. 1919",
    "Sterbejahr": 2011,
    "Sterbedatum/-ort": "<i>† 2011</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Bremen, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1935,
    "Emigrationsweg": "1935 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1935 emigr. to U.S."
  },
  {
    "PersonID": 24,
    "Name": "Ackermann, Werner (pseud. Rico Gala)",
    "Beruf": "author, translator",
    "Berufsgruppe": "Kunst, Sonstige",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1892,
    "Geburtsdatum/-ort": "* Antwerp, Belg. 28 Dec. 1892",
    "Sterbejahr": 1982,
    "Sterbedatum/-ort": "<i>† 1982</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Stadt(?), Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Türkei → 1933 Spanien → 1933 Belgien → 1951 Südafrika",
    "Emigrationsland": "Türkei, Spanien, Belgien, Südafrika",
    "Detailtext": "1933 emigr. to Belg. via Tur. and Sp. 1951 in Fed. Repub. Ger; resid. in Weinheim an der Bergstrasse. 1951 emigr. to Johannesburg. Novelist and dramatist; translator of Flemish and Dutch works incl. Stijn Streuvels, Elisabeth Zernike, and Anton Coolen. Contrib. to newspapers and journs. incl. Die Sammlung, Amsterdam."
  },
  {
    "PersonID": 25,
    "Name": "Adam, Leonhard",
    "Beruf": "prof. of anthropology, judge",
    "Berufsgruppe": "Sozialwissenschaften, Staatsdienst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1891,
    "Geburtsdatum/-ort": "* Berlin 16 Dec. 1891",
    "Sterbejahr": 1960,
    "Sterbedatum/-ort": "† Bonn 9 Sept. 1960 (on acad. vis).",
    "Religion": "Evangelical, fmly. Jewish",
    "Religion_Gruppe": "Jüdisch, Christlich",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1936,
    "Emigrationsweg": "1936 GB → 1940 Australien",
    "Emigrationsland": "GB, Australien",
    "Detailtext": "1936 emigr. to U.K. on vis. visa. Aided by ref. org. 1936–40 res. for the Colonial Off. Concurr: Lect, teacher, Univ. London; contrib. to anthro. period. Sept. 1940 res. for the Colonial Off. Concurr: Lect, teacher, Univ. London; contrib. to anthro. period. Sept. 1940–42 interned and transported to Tatura, Aust. Dir. of educ, teacher of anthro. and Chinese, Tatura."
  },
  {
    "PersonID": 26,
    "Name": "Adam, Wilhelm (Willi)",
    "Beruf": "Parteifunktionär",
    "Berufsgruppe": "Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1905,
    "Geburtsdatum/-ort": "* 26. Juli 1905 Ludenberg b. Düsseldorf",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "Diss.",
    "Religion_Gruppe": "Konfessionslos",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Saarbrücken (Saargebiet/Deutschland) → 1933 Frankreich → 1934 Dänemark → 1945 Berlin (Deutschland)",
    "Emigrationsland": "Saargebiet/Deutschland, Frankreich, Dänemark, Deutschland",
    "Detailtext": "1933 illeg. Tätigkeit, dann Emigr. ins Saargeb., 1934 (?) nach Dänemark, dort bis Ende 1945 Mitgl. BFD-Landeskomitee; Apr.–Mai 1945 Gestapo-Haft. Dez. 1945 nach Deutschland (SBZ), ltd. Tätigkeit beim Wiederaufbau der Landesverw. Mecklenburg-Vorpommern, dann pol. Mitarb. des ZK der SED, zuletzt Kunsterzieher an einer Ostberliner Hochschule."
  },
  {
    "PersonID": 27,
    "Name": "Adams (bis 1962 Cammnitzer), Ellen C.",
    "Beruf": "Parteifunktionärin",
    "Berufsgruppe": "Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1925,
    "Geburtsdatum/-ort": "* 1. Mai 1925 Hannover",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Hannover, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 GB → 1948 Kanada",
    "Emigrationsland": "GB, Kanada",
    "Detailtext": "1939 jüd. Schule in Hannover. Mitgl. der zionist. Jugendorg. Werkleute. März 1939 Emigr. nach GB, 1939–43 Büroangest. u. Fabrikarb., 1948 in der Verkehrsverw. für die brit. Besatzungszone; 1948 Dienst im Auxiliary Territorial Service. Daneben Stud. Exeter Univ. u. Univ. Göttingen u. Hannover. 1948 nach CDN, 1948–49 Buchhalterin in Ottawa."
  },
  {
    "PersonID": 28,
    "Name": "Adams, George (fmly. Georg Teltscher)",
    "Beruf": "graphic designer, professor",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1904,
    "Geburtsdatum/-ort": "* Vienna 1 July 1904",
    "Sterbejahr": 1983,
    "Sterbedatum/-ort": "<i>† 1983</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Hamburg, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Österreich → 1934 Spanien → 1938 GB → 1940 Australien → 1941 GB",
    "Emigrationsland": "Österreich, Spanien, GB, Australien",
    "Detailtext": "1933 freelance graphic designer in Berlin and Hamburg. 1933 returned to Aus. Resid. in Vienna. 1934 emigr. to Sp. 1934–36 art dir. at agcy. in Barcelona. 1938 emigr. to U.K. on tourist visa. Aided by Soc. of Friends, which provided a work permit. Lived in London. Freelance work. 1940 interned as enemy alien and shipped to Aust. 1941 returned to U.K. 1941–45 designer, Polit. Intell, Dept. of Fgn. Off. in London. Vol, Supreme Headquarters Allied Command in Eur; active in psych. warfare, coop. in Allied radio broadcasting."
  },
  {
    "PersonID": 29,
    "Name": "Adamson, (Joy) Friederike Victoria née Gessner, fmly. von Klarwill, fmly. Bally (pseuds. Joy Bally, Joy Adamson)",
    "Beruf": "author of books on wildlife, conservationist, painter",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1910,
    "Geburtsdatum/-ort": "* Troppau, Silesia, Aus. (Opava, C.S.R.) 20 Jan. 1910",
    "Sterbejahr": 1980,
    "Sterbedatum/-ort": "† Kenya 4 Jan. 1980 (murdered?).",
    "Religion": "Protestant",
    "Religion_Gruppe": "Christlich",
    "Ausreiseort": "Stadt(?), Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1937,
    "Emigrationsweg": "1937 Schweiz → 1937 Kenia [Kolonie GB]",
    "Emigrationsland": "Schweiz, Kenia",
    "Detailtext": "1937 emigr. alone and as vol. exile to Kenya via Switz. to find appropriate resid. for first husband, who was Jewish. Supported fam. in Kenya by self-taught painting and woodcarving."
  },
  {
    "PersonID": 30,
    "Name": "Adiel, Shraga (until 1955 Edelman)",
    "Beruf": "educator, director-general of Youth Aliyah",
    "Berufsgruppe": "Sozial-/Bildungswesen",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1913,
    "Geburtsdatum/-ort": "* Leipzig, Saxony, Ger. 21 June 1913",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1934,
    "Emigrationsweg": "1934 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1934 emigr. to Pal. with B-III cert. 1934–37 att. Hebrew Teachers Coll, Jerusalem."
  },
  {
    "PersonID": 31,
    "Name": "Adler, Alexandra",
    "Beruf": "dir. of institute, clinical prof. of psychiatry",
    "Berufsgruppe": "Medizin",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1901,
    "Geburtsdatum/-ort": "* Vienna 24 Sept. 1901",
    "Sterbejahr": 2001,
    "Sterbedatum/-ort": "<i>† 2001</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1935,
    "Emigrationsweg": "1935 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1935 intern, resid. and vis. physician, Univ. Vienna Neuropsychiatric Clin. Ed, Intl. Zft. für Individualpsych. 1935 emigr. to U.S. 1935–44 res. fel, assist. and instr. of neurol, Harvard Univ. Sch. of Med. Concurr: Grad. assist. in neurol, Massachusetts General Hosp; res. assoc. and sr. vis. physician, Boston City Hosp."
  },
  {
    "PersonID": 32,
    "Name": "Adler, Alfred",
    "Beruf": "prof. of mathematics",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Mathematik",
    "Geburtsjahr": 1930,
    "Geburtsdatum/-ort": "* Frankfurt/M 21 Feb. 1930",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1936,
    "Emigrationsweg": "1936 Italien → 1938 Frankreich → 1939 USA",
    "Emigrationsland": "Italien, Frankreich, USA",
    "Detailtext": "1936 emigr. to It. 1938 emigr. to Fr. Mar. 1939 to U.S. Att. Dartmouth Coll, Hanover, N. Hamp."
  },
  {
    "PersonID": 33,
    "Name": "Adler, Alfred",
    "Beruf": "neurologist, psychologist",
    "Berufsgruppe": "Medizin",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1870,
    "Geburtsdatum/-ort": "* Vienna 7 Feb. 1870",
    "Sterbejahr": 1937,
    "Sterbedatum/-ort": "† Aberdeen, Scot. 28 May 1937 (on lect. tour).",
    "Religion": "Protestant, fmly. Jewish",
    "Religion_Gruppe": "Jüdisch, Christlich",
    "Ausreiseort": "Stadt(?), Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1935,
    "Emigrationsweg": "1935 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1935 emigr. to U.S; subsequently div. yr. between U.S. and Eur. 1935?)–37 prof. of med. psych, Long Island Med. Coll. (now S.U.N.Y. Downstate Med. Cent.). Also lect: Temple Emanu-El, Vanderbilt Clin. of Columbia Presbyterian Med. Cent, and New School for Social Research, all New York. A.A. originated individual psychology and made a significant contribution to the study of compensation for organ inferiority. Earliest Synthesizer of Marxist and Freudian thought."
  },
  {
    "PersonID": 34,
    "Name": "Adler, Arthur M.",
    "Beruf": "Buchhändler",
    "Berufsgruppe": "Wirtschaft",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1899,
    "Geburtsdatum/-ort": "* 12. Febr. 1899 Höringhausen, Hessen-Nassau",
    "Sterbejahr": 1975,
    "Sterbedatum/-ort": "† 30. Aug. 1975 Schweiz",
    "Religion": "jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Spanien → 1936 Frankreich → 1942 USA",
    "Emigrationsland": "Spanien, Frankreich, USA",
    "Detailtext": "1933 Emigr. Spanien, 1936 Ansager bei dt.-sprach. Rundfunksender. 1936 Ausweisung nach Frankr., Buchhändler."
  },
  {
    "PersonID": 35,
    "Name": "Adler, Bruno (pseud. Urban Roedl)",
    "Beruf": "writer",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1889,
    "Geburtsdatum/-ort": "* Karlsbad, Bohemia, Aus. (Karlovy Vary, C.S.S.R.) 14 Oct. 1889",
    "Sterbejahr": 1968,
    "Sterbedatum/-ort": "† London 27 Dec. 1968",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Stadt(?), Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Prag (CSR/Tschechien) → 1936 GB",
    "Emigrationsland": "CSR/Tschechien, GB",
    "Detailtext": "1933 emigr. to Prague; 1936 emigr. to London. During W.W.II worked for Ger. sect, B.B.C."
  },
  {
    "PersonID": 36,
    "Name": "Adler, Emil",
    "Beruf": "prof. of physical medicine, prof. of physical rehabilitation",
    "Berufsgruppe": "Medizin",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1900,
    "Geburtsdatum/-ort": "* Prague 23 Sept. 1900",
    "Sterbejahr": 1971,
    "Sterbedatum/-ort": "† Jerusalem 4 Jan. 1971",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1939 emigr. to Pal. on A-I cert."
  },
  {
    "PersonID": 37,
    "Name": "Adler, Erich",
    "Beruf": "prof. of chemistry",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Chemie",
    "Geburtsjahr": 1905,
    "Geburtsdatum/-ort": "* Frankenreuth, Ger. 24 Oct. 1905",
    "Sterbejahr": 1985,
    "Sterbedatum/-ort": "<i>† 1985</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Mannheim, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Schweden",
    "Emigrationsland": "Schweden",
    "Detailtext": "1933 res. assist, Mannheim Munic. Hosp. lab. 1933 emigr. to Swed. 1933–44 mem. res. staff, Univ. Stockholm: 1933 res. assist, Biochem. Inst."
  },
  {
    "PersonID": 38,
    "Name": "Adler, Ernst",
    "Beruf": "lawyer, author",
    "Berufsgruppe": "Sozialwissenschaften, Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1903,
    "Geburtsdatum/-ort": "* Vienna 12 July 1903",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 Australien → 1960 Österreich → 1960 Berlin (Deutschland)",
    "Emigrationsland": "Australien, Österreich, Deutschland",
    "Detailtext": "1938 criminal lawyer in Vienna. 1938 emigr. to Sydney. Odd Jobs incl. laundry work, construction and metal work. 1960 returned to Vienna, then emigr. to Ger. Dem. Repub."
  },
  {
    "PersonID": 39,
    "Name": "Adler, Erving H.",
    "Beruf": "Bankier",
    "Berufsgruppe": "Wirtschaft",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1902,
    "Geburtsdatum/-ort": "* 19. Mai 1902 Hagenau. Elsaß",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1939 Emigr. USA. 1939–41 Büroangest. in Maklerbüro u. bei General Atlantic Steamship Co."
  },
  {
    "PersonID": 40,
    "Name": "Adler, Fred (Friedrich)",
    "Beruf": "Fabrikant",
    "Berufsgruppe": "Wirtschaft",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1888,
    "Geburtsdatum/-ort": "* 9. Sept. 1888 Brückenau, Bayern",
    "Sterbejahr": 1965,
    "Sterbedatum/-ort": "† 1965 New York",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 GB → 1933 USA",
    "Emigrationsland": "GB, USA",
    "Detailtext": "1938 Arisierung. Im Apr. 1939 Emigr. nach GB, anschl. in die USA. In Milwaukee Inh. einer Gerberei."
  },
  {
    "PersonID": 41,
    "Name": "Adler, Frederick Charles",
    "Beruf": "conductor",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1889,
    "Geburtsdatum/-ort": "* London 2 Jul. 1889",
    "Sterbejahr": 1959,
    "Sterbedatum/-ort": "† Vienna 1959",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Stadt(?), Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1937,
    "Emigrationsweg": "1937 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1937 fdr, Saratoga Springs Music Fests, N.Y. Radio cond. Prod. mgr. for publ. and recording businesses. Cond, New York Chamber Orch."
  },
  {
    "PersonID": 42,
    "Name": "Adler, Fred Peter",
    "Beruf": "Industriephysiker, Unternehmensleiter",
    "Berufsgruppe": "Exakte Wissenschaften, Wirtschaft",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Physik",
    "Geburtsjahr": 1925,
    "Geburtsdatum/-ort": "* 29. März 1925 Wien",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1942,
    "Emigrationsweg": "1942 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1942 Emigr. USA."
  },
  {
    "PersonID": 43,
    "Name": "Adler, Friedrich Wolfgang (Fritz), Dr. rer. nat.",
    "Beruf": "Politiker",
    "Berufsgruppe": "Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1879,
    "Geburtsdatum/-ort": "* 9. Juli 1879 Wien",
    "Sterbejahr": 1960,
    "Sterbedatum/-ort": "† 2. Jan. 1960 Zürich",
    "Religion": "Diss.",
    "Religion_Gruppe": "Konfessionslos",
    "Ausreiseort": "Zürich, Schweiz",
    "Ausreiseland": "Schweiz",
    "Ausreisejahr": 1935,
    "Emigrationsweg": "1935 Belgien → 1940 Frankreich → 1940 USA → 1946 Schweiz",
    "Emigrationsland": "Belgien, Frankreich, USA, Schweiz",
    "Detailtext": "1935 in Zürich, 1935–39 in Brüssel Sekr. SAI. 1940 unmittelbar vor dt. Einmarsch in Belgien nach Frankr., Verlegung der AVÖS von Paris nach Montauban/Südfrankr.; Sommer 1940 nach franz. Kapitulation mit falschem Paß auf den Namen Herzl Flucht über Spanien nach Lissabon, Okt. 1940 mit Notvisum nach New York."
  },
  {
    "PersonID": 44,
    "Name": "Adler, Gerson",
    "Beruf": "Verbandsfunktionär, Geschäftsmann",
    "Berufsgruppe": "Politik, Wirtschaft",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1927,
    "Geburtsdatum/-ort": "* 2. Okt. 1927 Berlin",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 USA",
    "Emigrationsland": "USA",
    "Detailtext": "."
  },
  {
    "PersonID": 45,
    "Name": "Adler, Helmut E(rnest)",
    "Beruf": "prof. of psychology",
    "Berufsgruppe": "Medizin",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1920,
    "Geburtsdatum/-ort": "* Nuremberg, Bavaria, Ger. 25 Nov. 1920",
    "Sterbejahr": 2001,
    "Sterbedatum/-ort": "<i>† 2001</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Nürnberg, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1935,
    "Emigrationsweg": "1935 GB → 1940 USA",
    "Emigrationsland": "GB, USA",
    "Detailtext": "1935 att. Gym, Nuremberg. 1935 emigr. to U.K. on student visa, att. sec. sch. 1940 part time courses at Burnley Munic. Coll. 1940 trainee, Lancashire Grinding Wheel Co, Burnley, Lancashire; also att. coll. part time. 1940 emigr. to U.S. to join mother, sisters and grandparents. Worked in grinding wheel co. and as welder in Wedge Bar Screen Co."
  },
  {
    "PersonID": 46,
    "Name": "Adler, Hermann",
    "Beruf": "writer",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1911,
    "Geburtsdatum/-ort": "* Deutsch-Diosek near Pressburg, Posony, Hung. (Bratislava, C.S.S.R.) 2 Oct. 1911",
    "Sterbejahr": 2001,
    "Sterbedatum/-ort": "<i>† 2001</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Landeshut, Deutschland/Polen",
    "Ausreiseland": "Deutschland/Polen",
    "Ausreisejahr": 1934,
    "Emigrationsweg": "1934 Prag (CSR/Tschechien) → 1939 Polen → 1940 Litauen → 1941 Polen → 1943 Ungarn → 1944 Deutschland → (Jahr ?) Schweiz",
    "Emigrationsland": "CSR/Tschechien, Polen, Litauen, Ungarn, Deutschland, Schweiz",
    "Detailtext": "1934 taught children with learning disabilities in Landeshut/Silesia. 1934 emigr. to C.S.R; freelance writer in Prague and Bratislava. 1939 emigr. to Cracow, Pol; joined the Czech legion. 1940 fled to Lwow, then to Vilna. 1941 in Vilna Ghetto, then Bialyastok and Warsaw Ghettos. Active in revolutionary groups. Partic. in the Warsaw Ghetto Rebellion. 1943 fled to Budapest. 1944 interned in Bergen-Belsen concentration camp. Dec. 1944– in Switz. Wrote many radio and television scripts. Mem: I.S.D.S; P.E.N."
  },
  {
    "PersonID": 47,
    "Name": "Adler, Israel",
    "Beruf": "library director, musicologist",
    "Berufsgruppe": "Geisteswissenschaften, Staatsdienst",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Kunst, Musik",
    "Geburtsjahr": 1925,
    "Geburtsdatum/-ort": "* Berlin 17 Jan. 1925",
    "Sterbejahr": 2009,
    "Sterbedatum/-ort": "<i>† 2009</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Berlin, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1937,
    "Emigrationsweg": "1937 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1937 emigr. to Pal."
  },
  {
    "PersonID": 48,
    "Name": "Adler, Jankel",
    "Beruf": "painter",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1895,
    "Geburtsdatum/-ort": "* Tuszyn near Lodz, Pol. 26 June 1895",
    "Sterbejahr": 1949,
    "Sterbedatum/-ort": "† Aldbourne near London 25 Apr. 1949",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Düsseldorf, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Frankreich → 1935 Polen → 1937 Frankreich → 1943 GB",
    "Emigrationsland": "Frankreich, Polen, GB",
    "Detailtext": "1933 in Düsseldorf: 1933 partic. in the exhib. of the Coll. Art Assn. C.A.A. at Rockefeller Cent, New York. 1933 emigr. to Paris due to racial persecution and discrimination as “degenerate” artist. Sojourn in Argèles-sur-Mer. Left fam. behind, met with Arthur Kaufmann and Teo Otto. 1935 emigr. to Pol. by traveling through Ger. Exhib. in Warsaw and Lodz after Pol. govt. helped rescue paintings from Düsseldorf storage. Trips to It, Balkan countries, and Moscow where he met Will Lammert. 1937 returned to Fr."
  },
  {
    "PersonID": 49,
    "Name": "Adler, Johann Anton",
    "Beruf": "Polizeibeamter",
    "Berufsgruppe": "Staatsdienst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1889,
    "Geburtsdatum/-ort": "* 23. Aug. 1889 Wien",
    "Sterbejahr": 1971,
    "Sterbedatum/-ort": "† 8. Nov. 1971 Den Haag",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 Niederlande → 1940 Brasilien → 1946 Niederlande",
    "Emigrationsland": "Niederlande, Brasilien",
    "Detailtext": "1938 Ltr. Interpol-Zentralstelle für Falschgeldbekämpfung in Wien. Gr. u. Ltr. des kriminalist. Labors der österr. Polizei, Gr. u. Red. der mehrsprachigen Fachzs. Counterfeits and Forgeries. 1938 Emigr. Niederlande, 1940 nach Brasilien, Tätigkeit bei der brasilian. Polizei. 1946 Rückkehr in die Niederlande, Berater des niederländ. Justizministeriums u. Ltr. einer Zentralstelle für Falschgeldbekämpfung der Interpol Den Haag. Chefred. Counterfeits and Forgeries."
  },
  {
    "PersonID": 50,
    "Name": "Adler, John Hans (bis 1941 Hans), Dr. jur., Ph.D.",
    "Beruf": "Ministerialbeamter",
    "Berufsgruppe": "Staatsdienst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1912,
    "Geburtsdatum/-ort": "* 16. Nov. 1912 Tachau, Böhmen",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Prag, CSR/Tschechien",
    "Ausreiseland": "CSR/Tschechien",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1938 Red. Die Wirtschaft. Mitarb. liberale Studentengruppe Lese- und Rede-Halle der deutschen Studenten, Prag. Okt. 1938 Emigr. nach USA, zunächst Studentenvisum, dann 1938–41 Stud. Columbia Univ."
  },
  {
    "PersonID": 51,
    "Name": "Adler, Julius",
    "Beruf": "prof. of biochemistry, prof. of genetics",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Biologie, Chemie",
    "Geburtsjahr": 1930,
    "Geburtsdatum/-ort": "* Edelfingen, Württemberg, Ger. 30 Apr. 1930",
    "Sterbejahr": 2024,
    "Sterbedatum/-ort": "<i>† 2024</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Edelfingen, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1938 emigr. with fam. to U.S."
  },
  {
    "PersonID": 52,
    "Name": "Adler, Karl",
    "Beruf": "dir. of music conservatory, conductor, music teacher",
    "Berufsgruppe": "Kunst, Sozial-/Bildungswesen",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1890,
    "Geburtsdatum/-ort": "* Buttenhausen, Württemberg, Ger. 25 Jan. 1890",
    "Sterbejahr": 1973,
    "Sterbedatum/-ort": "† New York 10 July 1973",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Stuttgart, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1940,
    "Emigrationsweg": "1940 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1940 head, Mittelstelle (emigr. adv.), Stuttgart where facilitated emigr. of Jews who had been imprisoned; recd. secret aid from non-Jewish sources incl. S. Bosch. 1940 emigr. to U.S. on non-quota visa with wife and parents. 1940 activities concerning further rescue of Württemberg Jews."
  },
  {
    "PersonID": 53,
    "Name": "Adler, Kenneth Paul (bis 1943 Kurt Paul Ernst), Ph.D.",
    "Beruf": "Ministerialbeamter, Hochschullehrer",
    "Berufsgruppe": "Staatsdienst, Sozial-/Bildungswesen",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1922,
    "Geburtsdatum/-ort": "* 20. Sept. 1922 Karlsruhe",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1937,
    "Emigrationsweg": "1937 GB → 1939 USA",
    "Emigrationsland": "GB, USA",
    "Detailtext": "1937 nach GB, Stud. Trent College, Derbyshire/GB. 2 1/2jährige Wartezeit für US-Visum. Febr. 1939 Emigr. USA mit älterer Schwester. Arbeitsvermittlung durch Selfhelp; Gelegenheitsarb., Assist. in Chemielabor."
  },
  {
    "PersonID": 54,
    "Name": "Adler, Kurt",
    "Beruf": "conductor, pianist",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1907,
    "Geburtsdatum/-ort": "* Neuhaus, Bohemia, Aus. (Jindrichuv Hradec, C.S.R.) 1 Mar. 1907",
    "Sterbejahr": 1977,
    "Sterbedatum/-ort": "† 21 Sept. 1977",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Moskau (UdSSR/Russland) → 1938 USA",
    "Emigrationsland": "UdSSR/Russland, USA",
    "Detailtext": "1933 cond, Dt. Musik-Bühne, Berlin. 1933 cond, Vienna Symph. Orch. 1933 emigr. to U.S.S.R. several days before Hitler seized power. 1933–35 head cond, Kiev State Opera. 1938 emigr. to U.S. Toured U.S. as pianist. 1938–43 cond. Bach concerts for Friendship House, New York."
  },
  {
    "PersonID": 55,
    "Name": "Adler, Kurt Herbert",
    "Beruf": "conductor, general music director, music administrator",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1905,
    "Geburtsdatum/-ort": "* Vienna 2 Apr. 1905",
    "Sterbejahr": 1988,
    "Sterbedatum/-ort": "<i>† 1988</i>",
    "Religion": "Protestant",
    "Religion_Gruppe": "Christlich",
    "Ausreiseort": "Salzburg, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1938 cond. for opera and radio in C.S.R; concurr. gave courses at intl. summer sch. at Salzburg Mozarteum. 1938 emigr. to U.S. 1938–43 cond, Chicago Civic Opera Co."
  },
  {
    "PersonID": 56,
    "Name": "Adler, Leo",
    "Beruf": "cantor",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1884,
    "Geburtsdatum/-ort": "* Braunsbach, Württemberg, Ger. 16 May 1884",
    "Sterbejahr": 1966,
    "Sterbedatum/-ort": "† New York 28 Mar. 1966",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Stuttgart, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1938 Oberkantor, Hauptlehrer, Stuttgart Jewish cmty. Oct. 1938 transported to Dachau concentration camp; freed after 4 weeks. 1938 emigr. to U.S."
  },
  {
    "PersonID": 57,
    "Name": "Adler, Leo, Dr. phil.",
    "Beruf": "Rabbiner",
    "Berufsgruppe": "Geistliche",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1915,
    "Geburtsdatum/-ort": "* 17. März 1915 Nürnberg",
    "Sterbejahr": 1978,
    "Sterbedatum/-ort": "† 12. Aug. 1978 Samaden, Schweiz",
    "Religion": "jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1935,
    "Emigrationsweg": "1935 Polen → 1939 Litauen → 1941 China → 1946 USA",
    "Emigrationsland": "Polen, Litauen, China, USA",
    "Detailtext": "1935 (?) nach Polen zum Besuch der Jeschiwah in Mir, die 1939 nach der sowjet. Besetzung nach Wilna/Litauen verlegt wurde. 1941 über die UdSSR u. Japan nach Schanghai, vermutl. mit Angehörigen der Jeschiwah Mir, die in Schanghai wiederaufgebaut wurde. Gr. einer koscheren Küche für jüd. Waisen in Schanghai. 1946 Ordination zum Rabbiner. 1946 Emigr. USA."
  },
  {
    "PersonID": 58,
    "Name": "Adler, Ludwig",
    "Beruf": "gynecologist",
    "Berufsgruppe": "Medizin",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1876,
    "Geburtsdatum/-ort": "* Vienna 7 Nov. 1876",
    "Sterbejahr": 1958,
    "Sterbedatum/-ort": "† U.S. 1958",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1938 head, Dept. of Gynecol, Wilhelminen Hosp, later on Rudolph-Hosp. and Bettina-Pavillion, Vienna. Sci. work in Aus. focused on pathol. of the uterus, ovarian functions, and treatment of uterine carcinoma. Earned international reputation as surgeon by discovering method for radical vaginal hysterectomy with implantation of radium into the parametria. 1938 emigr. to U.S."
  },
  {
    "PersonID": 59,
    "Name": "Adler, Max Kurt, Dr. rer. pol.",
    "Beruf": "Parteifunktionär, Marktanalytiker",
    "Berufsgruppe": "Politik, Sozialwissenschaften",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1905,
    "Geburtsdatum/-ort": "* 12. Juni 1905 Pilsen, Böhmen",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "Diss.",
    "Religion_Gruppe": "Konfessionslos",
    "Ausreiseort": "Pilsen, CSR/Tschechien",
    "Ausreiseland": "CSR/Tschechien",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 GB",
    "Emigrationsland": "GB",
    "Detailtext": "1938 Vertriebsmanager bei Josef Adler & Söhne, Pilsen. Okt. 1938 Emigr. nach GB."
  },
  {
    "PersonID": 60,
    "Name": "Adler, Peter Herman(n)",
    "Beruf": "conductor",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1899,
    "Geburtsdatum/-ort": "* Gablonz, Bohemia, Aus. (Jablonec, C.S.S.R.) 2 Dec. 1899",
    "Sterbejahr": 1990,
    "Sterbedatum/-ort": "<i>† 1990</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Stadt(?), Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1939 emigr. to U.S. 1939 debut with New York Philh."
  },
  {
    "PersonID": 61,
    "Name": "Adler, Peter T.",
    "Beruf": "dir. of mental health center",
    "Berufsgruppe": "Medizin",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1934,
    "Geburtsdatum/-ort": "* Vienna 5 July 1934",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "None, fmly. Roman Catholic",
    "Religion_Gruppe": "Christlich, Konfessionslos",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 GB → 1940 USA",
    "Emigrationsland": "GB, USA",
    "Detailtext": "1938 emigr. with mother to U.K, and 1940 with fam. to U.S."
  },
  {
    "PersonID": 62,
    "Name": "Adler, Robert",
    "Beruf": "research engineer",
    "Berufsgruppe": "Technik",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Technik",
    "Geburtsjahr": 1913,
    "Geburtsdatum/-ort": "* Vienna 4 Dec. 1913",
    "Sterbejahr": 2007,
    "Sterbedatum/-ort": "<i>† 2007</i>",
    "Religion": "None, fmly. until 1927 Jewish",
    "Religion_Gruppe": "Jüdisch, Konfessionslos",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 GB → 1940 USA",
    "Emigrationsland": "GB, USA",
    "Detailtext": "1939 emigr. to Belg; brief stay in Brussels. June 1939 emigr. to U.K. on vis. visa. Jan.–June 1940 engr. in electronics lab. for Sci. Acoustics Ltd, London. June 1940 emigr. to U.S. (fare paid by Quakers). 1940–41 head of lab, Assoc. Res. Inc, Chicago."
  },
  {
    "PersonID": 63,
    "Name": "Adler, Samuel Hans",
    "Beruf": "composer, prof. of composition",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1928,
    "Geburtsdatum/-ort": "* Mannheim, Baden, Ger. 4 Mar. 1928",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Stadt(?), Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1939 emigr. to U.S."
  },
  {
    "PersonID": 64,
    "Name": "Adler-Rudel, Salomon (Shalom)",
    "Beruf": "Sozialfürsorger, Publizist, Verbandsfunktionär",
    "Berufsgruppe": "Sozial-/Bildungswesen, Medien, Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1894,
    "Geburtsdatum/-ort": "* 23. Juni 1894 Czernowitz, Bukowina",
    "Sterbejahr": 1975,
    "Sterbedatum/-ort": "† 14. Nov. 1975 Jerusalem",
    "Religion": "jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1936,
    "Emigrationsweg": "1936 GB → 1949 Palästina/Israel",
    "Emigrationsland": "GB, Palästina/Israel",
    "Detailtext": "1936 Geschäftsf. Reichsvertretung u. Mitgl. des Hauptvorst. ZVfD. 1936 von Georg Kareski als Sozialist denunziert, Ausweisung, Emigr. GB. 1936–45 Mitgl. Haupt-Vorst. der brit. Abt. des Council für German Jewry u. als Abg. der Reichsvertretung Berater des Central Brit. Fund in London, tätig in Einwanderungshilfe, Juli 1936–45 Vize-Präs. Zion. Fed. of Great Britain, 1949 Vize-Präs. AJR London. 1949 nach Israel, 1949–55 Ltr. Abt. für Auslandsbeziehungen der Jew. Agency Jerusalem, IRO-Mitarb. für die Auswanderung von D.P."
  },
  {
    "PersonID": 65,
    "Name": "Adolf, Helen",
    "Beruf": "prof. of German",
    "Berufsgruppe": "Geisteswissenschaften",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Sprache",
    "Geburtsjahr": 1895,
    "Geburtsdatum/-ort": "* Vienna 31 Dec. 1895",
    "Sterbejahr": 1998,
    "Sterbedatum/-ort": "<i>† 1998</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1939 emigr. to U.S. Aided by rels. and Am. Friends Serv. Comm. 1939–40 att. summer sch, Univ. Pennsylvania to learn Sp."
  },
  {
    "PersonID": 66,
    "Name": "Adolph (urspr. Adolf), Alfred",
    "Beruf": "Parteifunktionär",
    "Berufsgruppe": "Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1895,
    "Geburtsdatum/-ort": "* 30. Juli 1895 Sommerfeld, Niederlausitz",
    "Sterbejahr": 1959,
    "Sterbedatum/-ort": "† 27. Apr. 1959 Berlin (Ost)",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Prag (CSR/Tschechien) → 1933 Moskau (UdSSR/Russland) → 1933 Niederlande → 1933 Frankreich → 1938 Schweiz → 1939 Frankreich → 1946 Deutschland",
    "Emigrationsland": "CSR/Tschechien, UdSSR/Russland, Niederlande, Frankreich, Schweiz, Deutschland",
    "Detailtext": "1938 Anmeldung als pol. Flüchtling in der Schweiz; Festnahme wegen pol. u. nachrichtendienstl. Tätigkeit. 1939 Verurteilung, Ausweisung. Deckn. Fritz, Berthold, Adolf, Schule, Robert. Ab Aug. 1946 über Paris nach Berlin."
  },
  {
    "PersonID": 67,
    "Name": "Adorno, Theodor W. (fmly. Wiesengrund)",
    "Beruf": "prof. of philosophy, prof. of sociology, musicologist",
    "Berufsgruppe": "Geisteswissenschaften, Sozialwissenschaften",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Philosophie, Kunst, Musik",
    "Geburtsjahr": 1903,
    "Geburtsdatum/-ort": "* Frankfurt/M 11 Sept. 1903",
    "Sterbejahr": 1969,
    "Sterbedatum/-ort": "† Brig, Wallis, Switz. 6 Aug. 1969",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Frankfurt/Main, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1934,
    "Emigrationsweg": "1934 GB → 1938 USA → 1949 Deutschland",
    "Emigrationsland": "GB, USA, Deutschland",
    "Detailtext": "1934 emigr. to U.K. Instr. at Oxford Univ. 1938 emigr. to New York as mem. of Inst. for Soc. Res, which was moved to and re-opened in U.S. Concurr. until 1949–50). Instr, Univ. California, Berkeley. 1949 dir. of Res. Projct on Soc. Discrimination in Los Angeles. 1949 returned to Ger. Resumed activities at Univ. Frankfurt/M and at Inst. for Soc. Res."
  },
  {
    "PersonID": 68,
    "Name": "Aenderl, Franz Xaver",
    "Beruf": "Publizist, Politiker",
    "Berufsgruppe": "Medien, Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1883,
    "Geburtsdatum/-ort": "* 25. Nov. 1883 Steinweg b. Regensburg",
    "Sterbejahr": 1951,
    "Sterbedatum/-ort": "† 20. Okt. 1951 Kulmbach, Oberfr.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Stadt(?), Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1934,
    "Emigrationsweg": "1934 Prag (CSR/Tschechien) → 1938 Polen → 1938 Dänemark → 1938 GB → 1946 Bayern (Deutschland)",
    "Emigrationsland": "CSR/Tschechien, Polen, Dänemark, GB, Deutschland",
    "Detailtext": "1934 Flucht in die CSR; 1938 über Polen u. Dänemark Emigr. nach GB. In London Journ."
  },
  {
    "PersonID": 69,
    "Name": "Aharoni (urspr. Aronheim), Yohanan, Ph.D.",
    "Beruf": "Archäologe, Hochschullehrer",
    "Berufsgruppe": "Geisteswissenschaften, Sozial-/Bildungswesen",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Archäologie",
    "Geburtsjahr": 1919,
    "Geburtsdatum/-ort": "* 7. Juni 1919 Frankfurt/O.",
    "Sterbejahr": 1976,
    "Sterbedatum/-ort": "† 1976 Tel Aviv",
    "Religion": "jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Frankfurt/Oder, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1933 Emigr. Israel mit B III-Zertifikat, 1933–35 Mitgl. HaNoar haOved u. Histadrut."
  },
  {
    "PersonID": 70,
    "Name": "Aladjem, Frederick",
    "Beruf": "prof. of biophysics, prof. of immunochemistry",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Biologie, Chemie, Physik",
    "Geburtsjahr": 1921,
    "Geburtsdatum/-ort": "* Vienna 8 Feb. 1921",
    "Sterbejahr": 2012,
    "Sterbedatum/-ort": "<i>† 2012</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Stadt(?), Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 Bulgarien → 1940 USA",
    "Emigrationsland": "Bulgarien, USA",
    "Detailtext": "1938 emigr. to Bulg. 1940 emigr. to U.S."
  },
  {
    "PersonID": 71,
    "Name": "Albeck, Chanoch",
    "Beruf": "rabbi, prof. of Talmud",
    "Berufsgruppe": "Geistliche, Geisteswissenschaften",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Religion, Fremdkulturen",
    "Geburtsjahr": 1890,
    "Geburtsdatum/-ort": "* Lowicz, Russ. Pol. (Pol.) 3 Aug. 1890",
    "Sterbejahr": 1972,
    "Sterbedatum/-ort": "† Jerusalem 9 Jan. 1972",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Berlin, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1935,
    "Emigrationsweg": "1935 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1935 lect, L.(H.)W.J. 1935 emigr. to Pal. with offer of post at Hebrew Univ."
  },
  {
    "PersonID": 72,
    "Name": "Albeck, Michael",
    "Beruf": "prof. of chemistry",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Chemie",
    "Geburtsjahr": 1934,
    "Geburtsdatum/-ort": "* Berlin 15 Oct. 1934",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Berlin, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1935,
    "Emigrationsweg": "1935 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1935 emigr. to Pal. with fam."
  },
  {
    "PersonID": 73,
    "Name": "Albeck, Shalom",
    "Beruf": "prof. of law, prof. of Talmud",
    "Berufsgruppe": "Sozialwissenschaften, Geisteswissenschaften",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Religion, Fremdkulturen",
    "Geburtsjahr": 1931,
    "Geburtsdatum/-ort": "* Berlin 4 Sept. 1931",
    "Sterbejahr": 2018,
    "Sterbedatum/-ort": "<i>† 2018</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Berlin, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1935,
    "Emigrationsweg": "1935 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1935 emigr. to Pal."
  },
  {
    "PersonID": 74,
    "Name": "Albers, Anni (Anneliese), née Fleischmann",
    "Beruf": "textile designer, commercial artist, graphic artist",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1899,
    "Geburtsdatum/-ort": "* Berlin 12 June 1899",
    "Sterbejahr": 1994,
    "Sterbedatum/-ort": "<i>† 1994</i>",
    "Religion": "Protestant",
    "Religion_Gruppe": "Christlich",
    "Ausreiseort": "Berlin, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1933 at Bauhaus Berlin-Steglitz; concurr. freelance weaving. 1933 emigr. to U.S, offered teaching position at Black Mountain Coll, N. Car; 1933–49 assist. prof. of art, Black Mountain Coll."
  },
  {
    "PersonID": 75,
    "Name": "Albers, Josef",
    "Beruf": "painter, professor",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1888,
    "Geburtsdatum/-ort": "* Bottrop, Westphalia, Ger. 19 Mar. 1888",
    "Sterbejahr": 1976,
    "Sterbedatum/-ort": "† New Haven, Conn. 25 Mar. 1976",
    "Religion": "Roman Catholic",
    "Religion_Gruppe": "Christlich",
    "Ausreiseort": "Stadt(?), Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1933 with Bauhaus: 1933 premature dismissal, then Bauhaus closed by Nazis. Purchases discontinued by City of Dessau. Same year accepted position as first Bauhaus artist at newly founded Black Mountain Coll, N. Car. (offered by John Andrew Rice with the encouragement of Philip C. Johnson of the Mus. of Modern Art, New York). Nov. 1933 emigr. with wife to U.S. on nonquota visa. Helped by Edward Warburg. 1933–49 mem. fac, Black Mountain Coll: 1933–49 instr, head of art dept, and teacher of Kenneth Noland, Robert Rauschenberg."
  },
  {
    "PersonID": 76,
    "Name": "Albert, John, Dr. jur.",
    "Beruf": "Journalist, Beamter",
    "Berufsgruppe": "Medien, Staatsdienst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1912,
    "Geburtsdatum/-ort": "* 28. Jan. 1912 Wien",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1940,
    "Emigrationsweg": "1940 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1940 Emigr. USA, 1940–42 Hilfsred. für Auslandsnachrichten bei Columbia Broadcasting System (CBS)."
  },
  {
    "PersonID": 77,
    "Name": "Albert, Peter Wenzel (von), Dr.",
    "Beruf": "Politiker",
    "Berufsgruppe": "Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": null,
    "Geburtsdatum/-ort": "k.A.",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": null,
    "Emigrationsweg": "(Jahr ?) GB",
    "Emigrationsland": "GB",
    "Detailtext": "Legitimist in Wien; Emigr. London."
  },
  {
    "PersonID": 78,
    "Name": "Alder, Henry Ludwig,(Heinrich)",
    "Beruf": "prof. of mathematics",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Mathematik",
    "Geburtsjahr": 1922,
    "Geburtsdatum/-ort": "* Duisburg, Rhineland, Ger. 26 Mar. 1922",
    "Sterbejahr": 2002,
    "Sterbedatum/-ort": "<i>† 2002</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Duisburg, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Schweiz → 1941 USA",
    "Emigrationsland": "Schweiz, USA",
    "Detailtext": "1933 emigr. to Switz. with fam. 1941 att. E.T.H. Zurich. 1941 emigr. to U.S. with fam; joined aunt already in U.S. 1941–47 att. Univ. California, Berkeley."
  },
  {
    "PersonID": 79,
    "Name": "Alewyn, Richard",
    "Beruf": "Germanist, literary historian, prof. of literature",
    "Berufsgruppe": "Geisteswissenschaften",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Sprache, Literatur, Geschichte",
    "Geburtsjahr": 1902,
    "Geburtsdatum/-ort": "* Frankfurt/M 24 Feb. 1902",
    "Sterbejahr": 1979,
    "Sterbedatum/-ort": "† Prien, Bavaria, Ger. 14 Aug. 1979",
    "Religion": "Protestant",
    "Religion_Gruppe": "Christlich",
    "Ausreiseort": "Heidelberg, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Frankreich → 1935 Österreich → 1938 Schweiz → 1939 USA → 1949 Deutschland",
    "Emigrationsland": "Frankreich, Österreich, Schweiz, USA, Deutschland",
    "Detailtext": "1933 dismissed from civil serv. because of Jewish descent and emigr. to Fr. 1933–35 Rockefeller schol. and vis. prof. at Sorbonne. 1935 Rockefeller schol. and vis. prof. at Sorbonne. 1935 emigr. to Aus. for econ. reasons. 1938 emigr. to Switz. Feb. 1939 emigr. to U.S. with fam. 1939–49 assoc. prof, Queens Coll, New York (C.U.N.Y.). 1949 assoc. prof, Queens Coll, New York (C.U.N.Y.). 1949 returned to Fed. Repub. Ger. and app. as o. Prof, Univ. Cologne."
  },
  {
    "PersonID": 80,
    "Name": "Alexander, Alexander (Sándor)",
    "Beruf": "Unternehmensleiter",
    "Berufsgruppe": "Wirtschaft",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1916,
    "Geburtsdatum/-ort": "* 21. Nov. 1916",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Prag, CSR/Tschechien",
    "Ausreiseland": "CSR/Tschechien",
    "Ausreisejahr": null,
    "Emigrationsweg": "(Jahr ?) GB",
    "Emigrationsland": "GB",
    "Detailtext": "Stud. Prag, Emigr. GB."
  },
  {
    "PersonID": 81,
    "Name": "Alexander, Edgar (fmly. Edgar Alexander Emmerich)",
    "Beruf": "journalist",
    "Berufsgruppe": "Medien",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1902,
    "Geburtsdatum/-ort": "* Saarbrücken, Saarland, Ger. 13 June 1902",
    "Sterbejahr": 1970,
    "Sterbedatum/-ort": "† New York 19 Jan. 1970",
    "Religion": "Roman Catholic",
    "Religion_Gruppe": "Christlich",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Vatikan (Italien) → 1933 Frankreich → 1933 USA",
    "Emigrationsland": "Vatikan, Frankreich, USA",
    "Detailtext": "Emigr. to Vatican City after Nazis came to power; later to Fr. Contrib. to Der Deutsche in Polen, Die neue Weltbühne, Das Neue Tage-Buch and others. Analyzed fascism from a Catholic-conservative viewpoint. Later emigr. to U.S."
  },
  {
    "PersonID": 82,
    "Name": "Alexander, Ernst",
    "Beruf": "prof. of applied physics",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Physik",
    "Geburtsjahr": 1902,
    "Geburtsdatum/-ort": "* Berlin 19 Mar. 1902",
    "Sterbejahr": 1980,
    "Sterbedatum/-ort": "<i>† 1980</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Freiburg, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1933 assist, Privatdoz, Phys.-Chem. Inst. Univ. Freiburg/Breisgau. 1933 emigr. to Pal. with vis. visa. 1933–74 mem. fac, dept. of phys, Hebrew Univ."
  },
  {
    "PersonID": 83,
    "Name": "Alexander, Gideon",
    "Beruf": "prof. of physics",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Physik",
    "Geburtsjahr": 1932,
    "Geburtsdatum/-ort": "* Berlin 31 Jan. 1932",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Berlin, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1934,
    "Emigrationsweg": "1934 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1934 emigr. to Pal. M. Sc, Hebrew Univ; Ph. D, Dublin Univ. and Dublin Inst. for Advanced Studies."
  },
  {
    "PersonID": 84,
    "Name": "Alexander, Ḥaim (fmly. Heinz Günther)",
    "Beruf": "composer, pianist",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1915,
    "Geburtsdatum/-ort": "* Berlin 9 Aug. 1915",
    "Sterbejahr": 2012,
    "Sterbedatum/-ort": "<i>† 2012</i>",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Stadt(?), Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1936,
    "Emigrationsweg": "1936 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1936 emigr. to Pal. on B-III cert. with help of Emil Hauser, principal, Pal. Cons. of Music (later called Rubin Acad. of Music). 1936–45 studied composition and music,."
  },
  {
    "PersonID": 85,
    "Name": "Alexander, Henry Joachim, Dr. phil., Dr. jur.",
    "Beruf": "Rechtsanwalt, Verbandsfunktionär",
    "Berufsgruppe": "Sozialwissenschaften, Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1897,
    "Geburtsdatum/-ort": "* 4. Jan. 1897",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Berlin, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": null,
    "Emigrationsweg": "(Jahr ?) GB",
    "Emigrationsland": "GB",
    "Detailtext": "1925–37 RA in Berlin; Emigr. GB."
  },
  {
    "PersonID": 86,
    "Name": "Alexander, Kurt, Dr. jur.",
    "Beruf": "Rechtsanwalt, Verbandsfunktionär",
    "Berufsgruppe": "Sozialwissenschaften, Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1892,
    "Geburtsdatum/-ort": "* 13. Aug. 1892 Krefeld",
    "Sterbejahr": 1962,
    "Sterbedatum/-ort": "† 18. Febr. 1962 New York",
    "Religion": "jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Krefeld, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 GB → 1949 USA",
    "Emigrationsland": "GB, USA",
    "Detailtext": "1939 Vors. SynGde. Krefeld, 1939 Emigr. GB, 1939–43 beim Jew. Central Info. Office (später Wiener Library), 1949 Geschäftsf. AJR, 1949 Geschäftsf. Council of Jews from Germany, 1949 Dir. URO London, Vors. Leo Baeck Loge des B’nai B’rith London. 1949 in die USA, 1949–62 Dir. URO New York, Vizepräs. A.F.J.C.E., VorstMitgl. Selfhelp, Mitgl. Jew. Philanthropic Fund."
  },
  {
    "PersonID": 87,
    "Name": "Alexander, Leo",
    "Beruf": "psychiatrist",
    "Berufsgruppe": "Medizin",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1905,
    "Geburtsdatum/-ort": "* Vienna 11 Oct. 1905",
    "Sterbejahr": 1985,
    "Sterbedatum/-ort": "<i>† 1985</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Stadt(?), Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 China → 1933 USA",
    "Emigrationsland": "China, USA",
    "Detailtext": "1933 to China on one yr. app; lect. Peiping Union Med. Coll, hosp. assoc. 1933 emigr. to U.S."
  },
  {
    "PersonID": 88,
    "Name": "Alexander, Paul Julius",
    "Beruf": "prof. of history",
    "Berufsgruppe": "Geisteswissenschaften",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Geschichte",
    "Geburtsjahr": 1910,
    "Geburtsdatum/-ort": "* Berlin 12 May 1910",
    "Sterbejahr": 1977,
    "Sterbedatum/-ort": "† Berkeley, Calif. 16 Dec. 1977",
    "Religion": "Jewish",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Köln, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Frankreich → 1935 USA",
    "Emigrationsland": "Frankreich, USA",
    "Detailtext": "1933 in Cologne. 1933 emigr. to Fr. on student visa. 1933–35 private secy. in Fr. Concurr. 1935 private secy. in Fr. Concurr. 1935 emigr. to U.S. via Can. 1935–40 att. Univs. Michigan and Harvard."
  },
  {
    "PersonID": 89,
    "Name": "Alexander, Peter",
    "Beruf": "prof. of radiobiology",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Biologie",
    "Geburtsjahr": 1922,
    "Geburtsdatum/-ort": "* Munich 27 Jan. 1922",
    "Sterbejahr": 1993,
    "Sterbedatum/-ort": "<i>† 1993</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "München, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 GB",
    "Emigrationsland": "GB",
    "Detailtext": "1933 emigr. with fam. to London."
  },
  {
    "PersonID": 90,
    "Name": "Alexander, Shlomo (Edgar)",
    "Beruf": "prof. of physics",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Physik",
    "Geburtsjahr": 1930,
    "Geburtsdatum/-ort": "* Freiburg, Baden, Ger. 4 Sept. 1930",
    "Sterbejahr": 1998,
    "Sterbedatum/-ort": "<i>† 1998</i>",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "Freiburg, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Palästina/Israel",
    "Emigrationsland": "Palästina/Israel",
    "Detailtext": "1933 emigr. to Pal. with fam."
  },
  {
    "PersonID": 91,
    "Name": "Alexander, Walter, Dr. jur.",
    "Beruf": "Kommunalbeamter, Verbandsfunktionär",
    "Berufsgruppe": "Staatsdienst, Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1878,
    "Geburtsdatum/-ort": "* 20. März 1878 Berlin",
    "Sterbejahr": 1949,
    "Sterbedatum/-ort": "† 20. Apr. 1949 New York",
    "Religion": "jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "Berlin, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 Frankreich → (Jahr ?) USA",
    "Emigrationsland": "Frankreich, USA",
    "Detailtext": "1933–38 VorstMitgl. Zentralausschuß für Hilfe und Aufbau, Kuratoriumsvors. Jüdisches Lehrhaus Berlin, Mitarb. in Verw. des Gemeindeblatts der Jüdischen Gemeinde Berlin. 1939 Emigr. Frankr., einige Jahre später in die USA."
  },
  {
    "PersonID": 92,
    "Name": "Alexich, Georg Maria (George M.V.), Dr. phil.",
    "Beruf": "Diplomat, Hochschullehrer",
    "Berufsgruppe": "Staatsdienst, Sozial-/Bildungswesen",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1893,
    "Geburtsdatum/-ort": "* 14. Sept. 1893 Wien",
    "Sterbejahr": 1949,
    "Sterbedatum/-ort": "† 15. Juli 1949 USA",
    "Religion": "kath.",
    "Religion_Gruppe": "Christlich",
    "Ausreiseort": "Stadt(?), Niederlande",
    "Ausreiseland": "Niederlande",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 Frankreich → 1940 USA",
    "Emigrationsland": "Frankreich, USA",
    "Detailtext": "1938 ständiger Geschäftsträger in den Niederlanden mit Akkreditierung für Belgien u. Luxemburg, in dieser Zeit Ernennung zum bevollmächtigten ao. Gesandten u. bevollmächtigten Min.; 1938 nach dem Anschluß Verzicht auf Bewerbung um Aufnahme in den dt. Außendienst, Entlassung, Emigr. Paris. 1938–40 Dir. einer pharmazeut. Fabrik. 1940 Dir. einer pharmazeut. Fabrik. 1940 Flucht in die USA vor dt. Auslieferungsbegehren. Stud. Georgetown Univ. Washington/D.C., Prom., Prof. für internat. vergleichendes Recht u. Diplomatie."
  },
  {
    "PersonID": 93,
    "Name": "Alfert, Max",
    "Beruf": "prof. of zoology",
    "Berufsgruppe": "Exakte Wissenschaften",
    "Bereich": "Exakte Wissenschaften",
    "Disziplin": "Biologie",
    "Geburtsjahr": 1921,
    "Geburtsdatum/-ort": "* Vienna 23 Apr. 1921",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "Roman Catholic",
    "Religion_Gruppe": "Christlich",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 Belgien → 1940 Frankreich → 1942 USA",
    "Emigrationsland": "Belgien, Frankreich, USA",
    "Detailtext": "1939 Matura, Vienna. 1939 emigr. to Belg. 1939–40 univ. student. 1940 univ. student. 1940 arrested after Nazi attack on Belg. and deported to Fr; interned for 2 years at St. Cyprien, Gurs and Les Milles concentration camps. 1942 emigr. to U.S. via Afr; recd. aid from Am. rels; worked as mechanic in war indus."
  },
  {
    "PersonID": 94,
    "Name": "Alfons, Anton",
    "Beruf": "Parteifunktionär",
    "Berufsgruppe": "Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1898,
    "Geburtsdatum/-ort": "* 17. Jan. 1898 Wampersdorf b. Mödling, Niederösterr.",
    "Sterbejahr": null,
    "Sterbedatum/-ort": "k.A.",
    "Religion": "Diss.",
    "Religion_Gruppe": "Konfessionslos",
    "Ausreiseort": "Stadt(?), Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 Norwegen → 1938 Schweden → 1946 Österreich",
    "Emigrationsland": "Norwegen, Schweden, Österreich",
    "Detailtext": "1938 im Parteiauftrag Emigr. nach Norwegen, später Schweden. Mitgl. KPÖ-Parteigruppe in Schweden. 1946 Rückkehr nach Österr., KPÖ-Funktionär in Baden b. Wien, Personalchef in USIA-Betrieb."
  },
  {
    "PersonID": 95,
    "Name": "Alfringhaus, Erich",
    "Beruf": "Journalist",
    "Berufsgruppe": "Medien",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1894,
    "Geburtsdatum/-ort": "* 30. Sept. 1894 Dortmund",
    "Sterbejahr": 1941,
    "Sterbedatum/-ort": "† 1941 Dänemark.",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1933,
    "Emigrationsweg": "1933 Dänemark",
    "Emigrationsland": "Dänemark",
    "Detailtext": "1933 Emigr. Dänemark."
  },
  {
    "PersonID": 96,
    "Name": "Alker, Ernst",
    "Beruf": "prof. of German literature, librarian",
    "Berufsgruppe": "Geisteswissenschaften, Staatsdienst",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Literatur",
    "Geburtsjahr": 1895,
    "Geburtsdatum/-ort": "* Vienna 22 Dec. 1895",
    "Sterbejahr": 1972,
    "Sterbedatum/-ort": "† Cademario, Switz. 5 Aug. 1972",
    "Religion": "Roman Catholic",
    "Religion_Gruppe": "Christlich",
    "Ausreiseort": "Berlin, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1934,
    "Emigrationsweg": "1934 Schweden → 1946 Schweiz",
    "Emigrationsland": "Schweden, Schweiz",
    "Detailtext": "1934 examiner, Prussian State Libr, Berlin. 1934 emigr. to Swed. after ciosing of Bonn Libr. Sch. by Nazis. 1934–42 lect. in Ger. lang. and lit. in Lund. 1946 lect. at cml. coll. in Stockholm. 1946 emigr. to Switz. 1946–69 mem. fac, Univ. Fribourg, Switz: 1946 a.o. Prof. of mod. Ger. lit."
  },
  {
    "PersonID": 97,
    "Name": "Allers, Franz",
    "Beruf": "conductor",
    "Berufsgruppe": "Kunst",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1905,
    "Geburtsdatum/-ort": "* Karlsbad, Bohemia, Aus. (Karlovy Vary, C.S.S.R.) 6 Aug. 1905",
    "Sterbejahr": 1995,
    "Sterbedatum/-ort": "<i>† 1995</i>",
    "Religion": "Unaffiliated, fmly. until 1922 Jewish",
    "Religion_Gruppe": "Jüdisch, Konfessionslos",
    "Ausreiseort": "München, Deutschland",
    "Ausreiseland": "Deutschland",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 GB → 1938 USA → 1973 Deutschland",
    "Emigrationsland": "GB, USA, Deutschland",
    "Detailtext": "1938 er.musical dir. of opera and cond. of philh. concerts, Munic. Theater, Usti, C.S.R. Concurr: Guest cond. with Czech. Philh. Orch, and with Prague Radio Symph. Orch; also guest cond. of opera and symph. concerts in Prague, Karlovy Vary and other Czech cities; org. youth concerts. June 1938 emigr. to U.K. Invited to join cond. staff of Ballet Russe de Monte Carlo. Oct. 1938 emigr. to U.S. 1938–39 freelance violinist, pianist. 1938–44 cond, Ballet Russe de Monte Carlo in U.S. and S. Am. Concurr: 1973 ret. to Fed. Repub. Ger."
  },
  {
    "PersonID": 98,
    "Name": "Allers, Rudolf",
    "Beruf": "philosopher, psychiatrist",
    "Berufsgruppe": "Geisteswissenschaften, Medizin",
    "Bereich": "Geisteswissenschaften",
    "Disziplin": "Philosophie",
    "Geburtsjahr": 1883,
    "Geburtsdatum/-ort": "* Vienna 13 Jan. 1883",
    "Sterbejahr": 1963,
    "Sterbedatum/-ort": "† Hyattsville, Md. 14 Dec. 1963",
    "Religion": "Roman Catholic",
    "Religion_Gruppe": "Christlich",
    "Ausreiseort": "Wien, Österreich",
    "Ausreiseland": "Österreich",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 USA",
    "Emigrationsland": "USA",
    "Detailtext": "1938 head, dept. of med. psych. and sensephysiol. at the Inst. of Physiol, the Univ. of Vienna Sch. of Med. Concur. cond. courses and lect. in univs. throughout Eur, incl. Sem. of Vienna and Catholic Univ, Salzburg. 1938 emigr. to U.S. 1938–48 prof. of philos. psych, Catholic Univ. of Am, Washington, D.C. Serv. for seven yrs. as expert in the Ecclesiastical Court of the Catholic Church, esp. in matrimonial cases."
  },
  {
    "PersonID": 99,
    "Name": "Alliger, Ladislaus",
    "Beruf": "Gewerkschaftler",
    "Berufsgruppe": "Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1898,
    "Geburtsdatum/-ort": "* 1898 (?)",
    "Sterbejahr": 1942,
    "Sterbedatum/-ort": "† 1942 in UK",
    "Religion": "k.A.",
    "Religion_Gruppe": "k.A.",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1938,
    "Emigrationsweg": "1938 GB",
    "Emigrationsland": "GB",
    "Detailtext": "Emigr. nach GB, Mitgl. DSAP-Auslandsgruppe."
  },
  {
    "PersonID": 100,
    "Name": "Allina, Heinrich",
    "Beruf": "Politiker, Gewerkschaftler",
    "Berufsgruppe": "Politik",
    "Bereich": null,
    "Disziplin": null,
    "Geburtsjahr": 1878,
    "Geburtsdatum/-ort": "* 24. Nov. 1878 Schaffa, Mähren",
    "Sterbejahr": 1953,
    "Sterbedatum/-ort": "† 10. Dez. 1953 Wien",
    "Religion": "1920 jüd.",
    "Religion_Gruppe": "Jüdisch",
    "Ausreiseort": "k.A.",
    "Ausreiseland": "k.A.",
    "Ausreisejahr": 1939,
    "Emigrationsweg": "1939 GB → 1949 Österreich",
    "Emigrationsland": "GB, Österreich",
    "Detailtext": "1939 (?) Emigr. London, Dez. 1939 Mitgr. Austria Office, nach Auseinandersetzung mit AVÖS in Paris, die ZusArb. mit legitimist. u. konservat. Gruppen ablehnte."
  }
];